platform :ios, '8.4'
use_frameworks!
target "TestPrj" do
	pod 'Masonry'
	pod 'ReactiveCocoa'
	pod 'AFNetworking'
	pod 'TTTAttributedLabel'
	pod 'IQKeyboardManager'
	pod 'MJExtension'
	pod 'Qiniu', '~> 7.0'
end